### ISSUE TITLE
How can I run it?

### ISSUE THREAD

**Issue by mjza** [rjperes/odata#1]
Hi there, Could you provide a README.md file that tells how can we run it?
I mean how can we migrate the Database and so on?

**Comment by rjperes** [comment]
Hi! Yes, I can do that.

**Comment by rjperes** [comment]
I will add a README soon, but what do you mean about running? The databases are created automatically by the code in Program, CreateDbIfNotExists.

**Comment by mjza** [comment]
In my case when I press on the run button in the Visual Studio 2019 it does not create the DB or tables. I need to do the migration first!
You almost answered in other issue the steps for migration. However in .Net 4.5 when we care similar oData projects, it will do the migrations before each run automatically. In the other ticket I also asked is there a way .Net Core to force Visual Studio to do this migration automatically without any command!?

**Comment by rjperes** [comment]
I have no idea of what your problem is, but it does create the database, I can prove it easily.
There is commented code to migrate the database, but you can't do both - create or migrate -, you need to choose.

**Comment by rjperes** [comment]
About your other question, even though this is OData, you need a controller to expose the data you want to serve. Mind you, this is not like WCF Data Services, where just exposed the DbContext and the data would be made available.

**Comment by rjperes** [comment]
Updated README
