### ISSUE TITLE
Invalid call for Blogs 

### ISSUE THREAD

**Issue by mjza** [rjperes/odata#2]
When I visit the following url [http://localhost:27179/odata/Blogs](http://localhost:27179/odata/Blogs) 
It will shows this error:

> An unhandled exception occurred while processing the request.
> SqlException: Invalid object name 'Blogs'.
> Microsoft.Data.SqlClient.SqlCommand+<>c.<ExecuteDbDataReaderAsync>b__164_0(Task<SqlDataReader> result)

**Comment by rjperes** [comment]
You need to update the database so as to create the tables, and then you will need to populate them.
To create the database run, on the command line:

dotnet ef database update

or, from the Package Manager Console inside Visual Studio:

Update-Database

Don't forget afterwards to add contents to the tables!

**Comment by mjza** [comment]
I am new to dot net core. In .Net it does the migration as soon as we run the app in visual studio. Is it possible to do a setting that in .Net core also it does the same?

**Comment by mjza** [comment]
Please don't forget to add `Microsoft.EntityFrameworkCore.Tools` to the project otherwise your command does not work!

**Comment by mjza** [comment]
It is interesting that there are 2 context in the DB, and we need to provide the name

`Update-Database -context BlogContext`
`Update-Database -context ParentChildContext`
