### ISSUE TITLE
2 urls do not work

### ISSUE THREAD

**Issue by mjza** [rjperes/odata#3]
When I run the app the following two urls work:

`https://localhost:44337/odata/Parents` and `https://localhost:44337/odata/Blogs`

However, the following two urls do not return any response:

`https://localhost:44337/odata/Posts` and `https://localhost:44337/odata/Children`

In the browser it says : 

>This localhost page can’t be found
>No webpage was found for the web address: https://localhost:44337/odata/Children
>HTTP ERROR 404

It is interesting that the first set of each context shown!

**Comment by rjperes** [comment]
But why should they work? None of those - Children or Posts - até exposed as entity collections! There are no controllers for them!

**Comment by mjza** [comment]
We are speaking about oData. In the metadata we have them as EntitySet:

```xml
<EntityContainer Name="Container">
<EntitySet Name="Parents" EntityType="odata.common.Parent">
<NavigationPropertyBinding Path="Children" Target="Children"/>
</EntitySet>
<EntitySet Name="Children" EntityType="odata.common.Child">
<NavigationPropertyBinding Path="Parent" Target="Parents"/>
</EntitySet>
<EntitySet Name="Blogs" EntityType="odata.common.Blog">
<NavigationPropertyBinding Path="Posts" Target="Posts"/>
</EntitySet>
<EntitySet Name="Posts" EntityType="odata.common.Post">
<NavigationPropertyBinding Path="Blog" Target="Blogs"/>
</EntitySet>
<FunctionImport Name="CountBlogPosts" Function="Default.CountBlogPosts" IncludeInServiceDocument="true"/>
</EntityContainer>
```

When I see them in the output I expected they response! Didn't know that you have not yet made the controller for them.

**Comment by rjperes** [comment]
You do. How would ASP.NET Core know how to retrieve them?
